### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by shillshocked** [romantomjak/translate#1]
runtime.main_main·f: function main is undeclared in the main package

**Comment by romantomjak** [comment]
Ooh, sorry for that. I'm using this as a library, but I'll provide an example and a sample command

**Comment by romantomjak** [comment]
I've had some free time and I've now fixed the installation problem + updated usage paragraph in the readme, have a look! This tool now supports environment variables too!

Try updating it via:
```sh
go get -u github.com/romantomjak/translate
```
Let me know if you experience any other issues!
